require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RefundsController do

  # This should return the minimal set of attributes required to create a valid
  # Refund. As you add validations to Refund, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all refunds as @refunds" do
      refund = Refund.create! valid_attributes
      get :index
      assigns(:refunds).should eq([refund])
    end
  end

  describe "GET show" do
    it "assigns the requested refund as @refund" do
      refund = Refund.create! valid_attributes
      get :show, :id => refund.id.to_s
      assigns(:refund).should eq(refund)
    end
  end

  describe "GET new" do
    it "assigns a new refund as @refund" do
      get :new
      assigns(:refund).should be_a_new(Refund)
    end
  end

  describe "GET edit" do
    it "assigns the requested refund as @refund" do
      refund = Refund.create! valid_attributes
      get :edit, :id => refund.id.to_s
      assigns(:refund).should eq(refund)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Refund" do
        expect {
          post :create, :refund => valid_attributes
        }.to change(Refund, :count).by(1)
      end

      it "assigns a newly created refund as @refund" do
        post :create, :refund => valid_attributes
        assigns(:refund).should be_a(Refund)
        assigns(:refund).should be_persisted
      end

      it "redirects to the created refund" do
        post :create, :refund => valid_attributes
        response.should redirect_to(Refund.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved refund as @refund" do
        # Trigger the behavior that occurs when invalid params are submitted
        Refund.any_instance.stub(:save).and_return(false)
        post :create, :refund => {}
        assigns(:refund).should be_a_new(Refund)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Refund.any_instance.stub(:save).and_return(false)
        post :create, :refund => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested refund" do
        refund = Refund.create! valid_attributes
        # Assuming there are no other refunds in the database, this
        # specifies that the Refund created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Refund.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => refund.id, :refund => {'these' => 'params'}
      end

      it "assigns the requested refund as @refund" do
        refund = Refund.create! valid_attributes
        put :update, :id => refund.id, :refund => valid_attributes
        assigns(:refund).should eq(refund)
      end

      it "redirects to the refund" do
        refund = Refund.create! valid_attributes
        put :update, :id => refund.id, :refund => valid_attributes
        response.should redirect_to(refund)
      end
    end

    describe "with invalid params" do
      it "assigns the refund as @refund" do
        refund = Refund.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Refund.any_instance.stub(:save).and_return(false)
        put :update, :id => refund.id.to_s, :refund => {}
        assigns(:refund).should eq(refund)
      end

      it "re-renders the 'edit' template" do
        refund = Refund.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Refund.any_instance.stub(:save).and_return(false)
        put :update, :id => refund.id.to_s, :refund => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested refund" do
      refund = Refund.create! valid_attributes
      expect {
        delete :destroy, :id => refund.id.to_s
      }.to change(Refund, :count).by(-1)
    end

    it "redirects to the refunds list" do
      refund = Refund.create! valid_attributes
      delete :destroy, :id => refund.id.to_s
      response.should redirect_to(refunds_url)
    end
  end

end
